version: '3.8'

services:
  backend:
    build:
      context: /fit_voyage_backend_nest
      dockerfile: Dockerfile
    container_name: fit_voyage_backend
    ports:
      - "3001:3001"
    env_file:
      - /fit_voyage_backend_nest/.env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      redis:
        condition: service_started
    networks:
      - fit_voyage_network
      - postgres_network
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: fit_voyage_redis_prod
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - fit_voyage_network
    restart: unless-stopped

volumes:
  redis_data:

networks:
  fit_voyage_network:
    driver: bridge
    name: fit_voyage_network
  postgres_network:
    external: true
    name: postgresql-u7pv_default
